// Source lists for kernel-net/build.rs (ours, M11).  Included from build.rs;
// kept separate so each file stays inside the 300-line rule.

const NETBSD_CSRCS: &[&str] = &[
    "sys/kern/subr_evcnt.c",
    "sys/kern/kern_mutex.c",
    "sys/kern/kern_condvar.c",
    "sys/kern/kern_rwlock.c",
    "sys/kern/kern_lock.c",
    "sys/kern/kern_timeout.c",
    "sys/kern/subr_psref.c",
    "sys/kern/subr_pool.c",
    "sys/kern/subr_hash.c",
    "sys/kern/subr_once.c",
    "sys/kern/subr_pserialize.c",
    "sys/kern/uipc_mbuf.c",
    "sys/kern/uipc_socket.c",
    "sys/kern/uipc_socket2.c",
    "sys/net/bpf_stub.c",
    "sys/net/if.c",
    "sys/net/if_llatbl.c",
    "sys/net/if_loop.c",
    "sys/net/if_stats.c",
    "sys/net/nd.c",
    "sys/net/radix.c",
    "sys/net/route.c",
    "sys/net/rtbl.c",
    "sys/netinet/cpu_in_cksum.c",
    "sys/netinet/if_arp.c",
    "sys/netinet/in.c",
    "sys/netinet/in4_cksum.c",
    "sys/netinet/in_cksum.c",
    "sys/netinet/in_offload.c",
    "sys/netinet/in_pcb.c",
    "sys/netinet/in_proto.c",
    "sys/netinet/ip_icmp.c",
    "sys/netinet/ip_input.c",
    "sys/netinet/ip_output.c",
    "sys/netinet/ip_reass.c",
    "sys/netinet/tcp_congctl.c",
    "sys/netinet/tcp_input.c",
    "sys/netinet/tcp_output.c",
    "sys/netinet/tcp_sack.c",
    "sys/netinet/tcp_subr.c",
    "sys/netinet/tcp_syncache.c",
    "sys/netinet/tcp_timer.c",
    "sys/netinet/tcp_usrreq.c",
    "sys/netinet/udp_usrreq.c",
];

/// Adapter files compiled for every arch (the shared ethernet ifnet core,
/// the stack glue and the boot tests).
const SHIM_CSRCS_COMMON: &[&str] = &[
    "rump_shim_lib.c",
    "rump_shim_mem.c",
    "rump_shim_time.c",
    "rump_shim_lock.c",
    "rump_shim_sleepq.c",
    "rump_shim_printf.c",
    "rump_shim_sysctl.c",
    "rump_shim_net.c",
    "rump_shim_if.c",
    "rump_shim_route.c",
    "rump_shim_sock.c",
    "rump_shim_softint.c",
    "rump_shim_inet.c",
    "rump_shim_misc.c",
    "rump_shim_ksock.c",
    "rump_shim_mobj.c",
    "rump_shim_init.c",
    "rump_domain.c",
    "rump_loss.c",
    "rump_loopback.c",
    "rump_ether_if.c",
    "rump_ether_ops.c",
    "rump_ip4.c",
    "rump_ping.c",
    "rump_udp.c",
    "rump_udp_host.c",
    "rump_tcp.c",
    "rump_tcp_io.c",
    "rump_tcp_conn.c",
    "rump_arp.c",
    "rump_dhcp.c",
    "rump_dhcp_pkt.c",
    "rump_dhcp_if.c",
    "rump_http.c",
    "rump_http_pkt.c",
    "rump_dns.c",
    "rump_dns_pkt.c",
    "rump_tools.c",
    "rump_r8.c",
    "rump_toolreq.c",
    "rump_selftest.c",
    "rump_md5.c",
];

/// x86_64 NIC: the QEMU e1000 behind the PCI hooks.
const SHIM_CSRCS_X86: &[&str] = &[
    "rump_e1000.c",
    "rump_e1000_dma.c",
    "rump_e1000_if.c",
];

/// aarch64 NIC: virtio-net over the modern MMIO transport.
const SHIM_CSRCS_AARCH64: &[&str] = &[
    "rump_virtio_net.c",
    "rump_virtio_net_dma.c",
    "rump_virtio_net_if.c",
];

/// TLS adapter files, compiled only under CONFIG_TLS with FANTUAN_TLS=1.
const TLS_CSRCS: &[&str] = &[
    "rump_tls_entropy.c",
    "rump_tls_kat.c",
    "rump_tls.c",
    "rump_tls_io.c",
    "rump_tls_conf.c",
    "rump_tls_pkt.c",
    "rump_ext.c",
];

/// The minimal mbedTLS subset for the kernel TLS client (M11 R8).  Compiled
/// with the same freestanding flags as the imported rump slice but from the
/// pristine tarball in apps/mbedtls/src/.
const MBEDTLS_CSRCS: &[&str] = &[
    "aes.c",
    "asn1parse.c",
    "asn1write.c",
    "bignum.c",
    "bignum_core.c",
    "bignum_mod.c",
    "bignum_mod_raw.c",
    "cipher.c",
    "cipher_wrap.c",
    "constant_time.c",
    "ctr_drbg.c",
    "ecdh.c",
    "ecp.c",
    "ecp_curves.c",
    "entropy.c",
    "error.c",
    "gcm.c",
    "md.c",
    "oid.c",
    "pk.c",
    "pk_ecc.c",
    "pk_wrap.c",
    "pkparse.c",
    "platform.c",
    "platform_util.c",
    "rsa.c",
    "rsa_alt_helpers.c",
    "sha256.c",
    "ssl_ciphersuites.c",
    "ssl_client.c",
    "ssl_msg.c",
    "ssl_tls.c",
    "ssl_tls12_client.c",
    "x509.c",
    "x509_crt.c",
];
