//! Build the NetBSD rump slice + the fantuan adaptation layer as one static
//! archive, compiled with clang for x86_64-unknown-none against the R1 shim
//! headers. The crate is only wired into the x86_64 kernel for now; other
//! build targets skip the C compile entirely.
//!
//! The imported sources keep upstream warnings (exempt from the repo's
//! zero-warning rule); the adapter files are compiled with -Wall -Wextra.

use std::env;
use std::path::Path;
use std::process::Command;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tools/kconfig_emit.rs"));

// The source lists live in build_lists.rs (size rule); cargo tracks it
// via the rerun-if-changed line in main().
include!("build_lists.rs");

const MBEDTLS_VERSION: &str = "3.6.7";

/// Generate OUT_DIR/tls_extra.rs for every target: the pinned CA (when the
/// smoke generated one under build/smoke-net-tls/) and the offline-fixture
/// flag (FANTUAN_NET_FIXTURES=1 in the smoke phases).
fn tls_extra(dir: &str, out: &str) {
    let root = format!("{dir}/..");
    let ca_path = format!("{root}/build/smoke-net-tls/ca.der");
    println!("cargo:rerun-if-changed={ca_path}");
    println!("cargo:rerun-if-env-changed=FANTUAN_NET_FIXTURES");
    let fixtures = std::env::var("FANTUAN_NET_FIXTURES").as_deref() == Ok("1");
    let ca = std::fs::read(&ca_path).unwrap_or_default();
    let mut gen = String::from("// Generated by kernel-net/build.rs (M11 R8) - do not edit.\n");
    gen.push_str(&format!(
        "#[allow(dead_code)]\npub static TLS_CA_DER: &[u8] = &{:?};\n",
        ca
    ));
    gen.push_str(&format!(
        "#[allow(dead_code)]\npub const NET_FIXTURES: bool = {fixtures};\n"
    ));
    std::fs::write(format!("{out}/tls_extra.rs"), gen).unwrap();
}

fn main() {
    kconfig_emit();
    let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let target = env::var("TARGET").unwrap();
    let out = env::var("OUT_DIR").unwrap();
    let netbsd = format!("{dir}/../third_party/netbsd");
    let shim = format!("{netbsd}/shim/include");
    let tls = kconfig_value("tls");

    println!("cargo:rerun-if-changed={dir}/build_lists.rs");
    tls_extra(&dir, &out);

    for f in NETBSD_CSRCS {
        println!("cargo:rerun-if-changed={netbsd}/{f}");
    }
    for f in SHIM_CSRCS {
        println!("cargo:rerun-if-changed={dir}/src/c/{f}");
    }
    for f in TLS_CSRCS {
        println!("cargo:rerun-if-changed={dir}/src/c/{f}");
    }
    println!("cargo:rerun-if-changed={dir}/src/c/rump_shim.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_dhcp.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_dns.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_http.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_tls.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_ext.h");
    println!("cargo:rerun-if-changed={dir}/src/c/rump_udp_host.h");
    println!("cargo:rerun-if-changed={dir}/src/c/fantuan_mbedtls_config.h");
    for h in ["assert.h", "string.h", "stdlib.h", "stdio.h", "time.h", "inttypes.h"] {
        println!("cargo:rerun-if-changed={dir}/src/c/mbedtls_shim/{h}");
    }
    println!("cargo:rerun-if-changed={shim}/machine/mutex.h");
    println!("cargo:rerun-if-changed={shim}/machine/cpu.h");
    println!("cargo:rerun-if-changed={shim}/ether.h");
    println!("cargo:rerun-if-changed={shim}/bridge.h");
    println!("cargo:rerun-if-changed={shim}/carp.h");
    println!("cargo:rerun-if-changed={shim}/arp.h");
    println!("cargo:rerun-if-changed={shim}/arcnet.h");
    println!("cargo:rerun-if-changed={shim}/gif.h");
    println!("cargo:rerun-if-changed={shim}/gre.h");
    println!("cargo:rerun-if-changed={shim}/pfsync.h");
    for h in [
        "faith.h",
        "sys/file.h",
        "sys/filedesc.h",
        "sys/poll.h",
        "sys/kthread.h",
        "sys/buf.h",
        "sys/md5.h",
        "uvm/uvm_loan.h",
        "uvm/uvm_page.h",
        "net/if_faith.h",
        "netinet/sctp_route.h",
        "netinet6/nd6.h",
        "netinet6/scope6_var.h",
        "netinet6/in6_offload.h",
        "netinet6/ip6protosw.h",
        "netipsec/ipsec.h",
        "netipsec/ipsec6.h",
        "netipsec/key.h",
        "ddb/db_active.h",
        "compat/sys/socket.h",
    ] {
        println!("cargo:rerun-if-changed={shim}/{h}");
    }

    if target != "x86_64-unknown-none" {
        return;
    }

    let resource = Command::new("clang")
        .arg("-print-resource-dir")
        .output()
        .expect("clang is required to build the NetBSD rump slice");
    let resource = String::from_utf8(resource.stdout).unwrap();
    let resource = resource.trim();
    assert!(Path::new(resource).exists(), "clang resource dir missing");

    let base = |warnings: bool| {
        let mut build = cc::Build::new();
        build
            .compiler("clang")
            .archiver("llvm-ar")
            .warnings(warnings)
            .flag(format!("--target={target}"))
            .flag("-ffreestanding")
            .flag("-nostdinc")
            .flag("-isystem")
            .flag(format!("{resource}/include"))
            .flag("-mno-red-zone")
            /* Match the Rust kernel's soft-float ABI: the BIOS boot path
             * does not enable CR4.OSFXSR, so SSE would fault with #UD. */
            .flag("-mno-sse")
            .flag("-mno-sse2")
            .flag("-mno-mmx")
            .flag("-msoft-float")
            .flag("-fno-stack-protector")
            .flag("-fno-builtin")
            .flag("-fno-pic")
            .flag("-fno-pie")
            .flag("-mcmodel=large")
            .flag("-ffunction-sections")
            .flag("-fdata-sections")
            .flag("-D_KERNEL")
            /* The sources are NetBSD's; the target triple is not.  __NetBSD__
             * selects the NetBSD-specific paths in shared headers (e.g. the
             * 802.11 ioctl numbers), INET the IPv4 stack paths. */
            .flag("-D__NetBSD__")
            .flag("-DINET=1")
            .include(&shim)
            .include(format!("{netbsd}/sys"))
            .include(format!("{netbsd}/common/include"))
            .include(format!("{dir}/src/c"));
        build
    };

    let mut imported = base(false);
    for f in NETBSD_CSRCS {
        imported.file(format!("{netbsd}/{f}"));
    }
    imported.compile("rumpobj");

    let mut adapter = base(true);
    /* -Wextra flags unused parameters inside the imported NetBSD headers
     * (inline helpers the adapter only includes); keep the rest of -Wall
     * -Wextra for our own files. */
    adapter.flag("-Wno-unused-parameter");
    if tls {
        adapter.flag("-DFANTUAN_TLS=1");
    }
    for f in SHIM_CSRCS {
        adapter.file(format!("{dir}/src/c/{f}"));
    }
    adapter.compile("rumpobj_shim");

    if tls {
        let mb_src = format!("{out}/mbedtls-src");
        let mb_root = format!("{mb_src}/mbedtls-{MBEDTLS_VERSION}");
        let tarball =
            format!("{dir}/../apps/mbedtls/src/mbedtls-{MBEDTLS_VERSION}.tar.bz2");
        println!("cargo:rerun-if-changed={tarball}");
        if !Path::new(&format!("{mb_root}/library/aes.c")).exists() {
            std::fs::create_dir_all(&mb_src).unwrap();
            let status = Command::new("tar")
                .arg("xjf")
                .arg(&tarball)
                .arg("-C")
                .arg(&mb_src)
                .arg(format!("mbedtls-{MBEDTLS_VERSION}/include"))
                .arg(format!("mbedtls-{MBEDTLS_VERSION}/library"))
                .status()
                .expect("tar is required to extract the mbedTLS tarball");
            assert!(status.success(), "mbedTLS tarball extraction failed");
        }
        for f in MBEDTLS_CSRCS {
            println!("cargo:rerun-if-changed={mb_root}/library/{f}");
        }
        // mbedTLS gets its own include path (no NetBSD headers, so
        // __has_include does not pick the kernel sys/socket.h and the
        // software inet_pton fallback is used).
        let mut mbed = cc::Build::new();
        mbed.compiler("clang")
            .archiver("llvm-ar")
            .warnings(false)
            .flag(format!("--target={target}"))
            .flag("-ffreestanding")
            .flag("-nostdinc")
            .flag("-isystem")
            .flag(format!("{resource}/include"))
            .flag("-mno-red-zone")
            .flag("-mno-sse")
            .flag("-mno-sse2")
            .flag("-mno-mmx")
            .flag("-msoft-float")
            .flag("-fno-stack-protector")
            .flag("-fno-builtin")
            .flag("-fno-pic")
            .flag("-fno-pie")
            .flag("-mcmodel=large")
            .flag("-ffunction-sections")
            .flag("-fdata-sections")
            .flag("-D_KERNEL")
            .flag("-DMBEDTLS_CONFIG_FILE=\"fantuan_mbedtls_config.h\"")
            .include(format!("{mb_root}/include"))
            .include(format!("{dir}/src/c/mbedtls_shim"))
            .include(format!("{dir}/src/c"));
        for f in MBEDTLS_CSRCS {
            mbed.file(format!("{mb_root}/library/{f}"));
        }
        mbed.compile("rumpobj_mbedtls");

        let mut tlsadapter = base(true);
        tlsadapter.flag("-Wno-unused-parameter");
        tlsadapter.flag("-DFANTUAN_TLS=1");
        tlsadapter.include(format!("{mb_root}/include"));
        tlsadapter.include(format!("{dir}/src/c/mbedtls_shim"));
        tlsadapter.flag("-DMBEDTLS_CONFIG_FILE=\"fantuan_mbedtls_config.h\"");
        for f in TLS_CSRCS {
            tlsadapter.file(format!("{dir}/src/c/{f}"));
        }
        tlsadapter.compile("rumpobj_tls");
    }
}
