//! Build-time codegen (DESIGN.md §13.3):
//!   1. parse kernel/src/consts.rs -> OUT_DIR/asm_defs.inc (single source of
//!      truth for assembly constants),
//!   2. generate OUT_DIR/isr_table.rs (extern stubs + address table),
//!   3. compile boot/entry.S + kernel/src/asm/interrupts.S via cc (the host
//!      driver preprocesses them, so they can #include asm_defs.inc).
//! Also tracks link.ld so cargo relinks when it changes.

use std::env;
use std::fs;

fn main() {
    let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    println!("cargo:rerun-if-changed={dir}/link.ld");
    println!("cargo:rerun-if-changed={dir}/src/consts.rs");
    println!("cargo:rerun-if-changed={dir}/src/asm/interrupts.S");
    println!("cargo:rerun-if-changed={dir}/src/asm/switch.S");
    println!("cargo:rerun-if-changed={dir}/src/asm/syscall.S");
    println!("cargo:rerun-if-changed={dir}/../boot/entry.S");
    println!("cargo:rustc-link-arg=-T{dir}/link.ld");

    let out = env::var("OUT_DIR").unwrap();

    // 1. asm_defs.inc: "pub const NAME: TYPE = VALUE;" -> ".equ NAME, VALUE"
    let consts = fs::read_to_string(format!("{dir}/src/consts.rs")).unwrap();
    let mut inc =
        String::from("/* Generated by kernel/build.rs from kernel/src/consts.rs - do not edit. */\n");
    for line in consts.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("pub const ") {
            let eq = rest.find('=').unwrap();
            let name = rest[..eq].split(':').next().unwrap().trim();
            let value = rest[eq + 1..].trim_end_matches(';').trim().replace('_', "");
            inc.push_str(&format!(".equ {name}, {value}\n"));
        }
    }
    fs::write(format!("{out}/asm_defs.inc"), inc).unwrap();

    // 2. isr_table.rs: extern stubs + a 256-entry address table
    let mut table = String::from("// Generated by kernel/build.rs - do not edit.\n\n");
    table.push_str("extern \"C\" {\n");
    for n in 0..256u16 {
        table.push_str(&format!("    fn isr_{n}();\n"));
    }
    table.push_str("}\n\npub fn isr_addresses() -> [u64; 256] {\n    [\n");
    for n in 0..256u16 {
        table.push_str(&format!("        isr_{n} as *const () as usize as u64,\n"));
    }
    table.push_str("    ]\n}\n");
    fs::write(format!("{out}/isr_table.rs"), table).unwrap();

    // 3. compile the assembly into a static archive for the kernel link
    cc::Build::new()
        .file(format!("{dir}/../boot/entry.S"))
        .file(format!("{dir}/src/asm/interrupts.S"))
        .file(format!("{dir}/src/asm/switch.S"))
        .file(format!("{dir}/src/asm/syscall.S"))
        .include(&out)
        .compile("bootasm");
}
