//! Build-time codegen (DESIGN.md §13.3):
//!   1. parse kernel/src/consts.rs -> OUT_DIR/asm_defs.inc (single source of
//!      truth for assembly constants),
//!   2. generate OUT_DIR/isr_table.rs (extern stubs + address table),
//!   3. compile boot/entry.S + kernel/src/arch/x86_64/asm/interrupts.S via cc (the host
//!      driver preprocesses them, so they can #include asm_defs.inc).
//! Also tracks link.ld so cargo relinks when it changes.

use std::env;
use std::fs;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tools/kconfig_emit.rs"));

fn main() {
    kconfig_emit();
    let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    println!("cargo:rerun-if-changed={dir}/link.ld");
    println!("cargo:rerun-if-changed={dir}/src/consts.rs");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/interrupts.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/isr_stubs.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/switch.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/syscall.S");
    println!("cargo:rerun-if-changed={dir}/../boot/entry.S");
    println!("cargo:rustc-link-arg=-T{dir}/link.ld");

    let out = env::var("OUT_DIR").unwrap();

    // 1. asm_defs.inc: "pub const NAME: TYPE = VALUE;" -> ".equ NAME, VALUE"
    let consts = fs::read_to_string(format!("{dir}/src/consts.rs")).unwrap();
    let mut inc =
        String::from("/* Generated by kernel/build.rs from kernel/src/consts.rs - do not edit. */\n");
    for line in consts.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("pub const ") {
            let eq = rest.find('=').unwrap();
            let name = rest[..eq].split(':').next().unwrap().trim();
            let value = rest[eq + 1..].trim_end_matches(';').trim().replace('_', "");
            inc.push_str(&format!(".equ {name}, {value}\n"));
        }
    }
    fs::write(format!("{out}/asm_defs.inc"), inc).unwrap();

    // 2. isr_table.rs: extern stubs + a 256-entry address table
    let mut table = String::from("// Generated by kernel/build.rs - do not edit.\n\n");
    table.push_str("extern \"C\" {\n");
    for n in 0..256u16 {
        table.push_str(&format!("    fn isr_{n}();\n"));
    }
    table.push_str("}\n\npub fn isr_addresses() -> [u64; 256] {\n    [\n");
    for n in 0..256u16 {
        table.push_str(&format!("        isr_{n} as *const () as usize as u64,\n"));
    }
    table.push_str("    ]\n}\n");
    fs::write(format!("{out}/isr_table.rs"), table).unwrap();

    // 3. embed the user program (built by tools/build.sh before the kernel).
    // P1: the libc-fantuan C hello (tools/build-libc.sh) is embedded when
    // present; a missing artifact leaves HELLO_ELF empty so default builds
    // are unchanged.
    let user = format!("{dir}/user_program.bin");
    println!("cargo:rerun-if-changed={user}");
    if !std::path::Path::new(&user).exists() {
        panic!(
            "kernel/user_program.bin is missing — build the user crate first (tools/build.sh or tools/run.sh)"
        );
    }
    let hello = format!("{dir}/hello_program.bin");
    println!("cargo:rerun-if-changed={hello}");
    let mut gen = format!("pub static USER_ELF: &[u8] = include_bytes!({user:?});\n");
    if std::path::Path::new(&hello).exists() {
        gen.push_str(&format!("pub static HELLO_ELF: &[u8] = include_bytes!({hello:?});\n"));
    } else {
        gen.push_str("pub static HELLO_ELF: &[u8] = &[];\n");
    }
    // P2: the process-layer test program (user/proc_test.c) shares the hello
    // embedding path; absent builds skip the P2 smoke markers.
    let proc_test = format!("{dir}/proc_test_program.bin");
    println!("cargo:rerun-if-changed={proc_test}");
    if std::path::Path::new(&proc_test).exists() {
        gen.push_str(&format!("pub static PROC_ELF: &[u8] = include_bytes!({proc_test:?});\n"));
    } else {
        gen.push_str("pub static PROC_ELF: &[u8] = &[];\n");
    }
    // P2: /bin/dash (tools/build-dash.sh, vendored BSD-3-Clause) is embedded
    // the same way; absent, the registry stays empty and `sh` falls back.
    let dash = format!("{dir}/dash_program.bin");
    println!("cargo:rerun-if-changed={dash}");
    if std::path::Path::new(&dash).exists() {
        gen.push_str(&format!("pub static DASH_ELF: &[u8] = include_bytes!({dash:?});\n"));
    } else {
        gen.push_str("pub static DASH_ELF: &[u8] = &[];\n");
    }
    // P3: /bin/bash (tools/build-bash.sh, GPLv3 app layer) is an ordinary user
    // program embedded like dash; it is never linked into the kernel or base
    // libraries (APPS.md GPL firewall) - but note the image then *contains*
    // its bytes, which THIRD_PARTY.md records as a deliberate exception.
    // tools/build.sh always produces the artifact and sets
    // FANTUAN_REQUIRE_BASH, so the default build fails loudly when it is
    // missing; a bare `cargo build` only warns and `sh` keeps dash.
    let bash = format!("{dir}/bash_program.bin");
    println!("cargo:rerun-if-changed={bash}");
    println!("cargo:rerun-if-env-changed=FANTUAN_REQUIRE_BASH");
    if !kconfig_value("bash") {
        // CONFIG_BASH=n: never embed it, even when a stale artifact exists.
        println!(
            "cargo:warning=CONFIG_BASH=n: building without the embedded shell \
             (/bin/dash is the fallback)"
        );
        gen.push_str("pub static BASH_ELF: &[u8] = &[];\n");
    } else if std::path::Path::new(&bash).exists() {
        gen.push_str(&format!("pub static BASH_ELF: &[u8] = include_bytes!({bash:?});\n"));
    } else if std::env::var("FANTUAN_REQUIRE_BASH").is_ok() {
        panic!(
            "kernel/bash_program.bin is missing — run tools/fetch-bash-src.sh && \
             tools/build-bash.sh (or just tools/build.sh), or build without the \
             embedded shell with CONFIG_BASH=n / FANTUAN_BUILD_BASH=0"
        );
    } else {
        println!(
            "cargo:warning=kernel/bash_program.bin is absent: /bin/sh will fall back to dash \
             (tools/build.sh builds and embeds bash by default)"
        );
        gen.push_str("pub static BASH_ELF: &[u8] = &[];\n");
    }
    // The sha256 of the embedded bash program (written by tools/build-bash.sh
    // next to the blob). Deliberately not named after the shell: smoke-gpl.sh
    // grep -i's the ELF's symbol table for shell symbols, and a symbol like
    // BASH_ELF_SHA256 would trip its own firewall check. With CONFIG_BASH=n the
    // marker is left out too, so the no-shell image carries no trace of the
    // shell (tools/smoke-config.sh asserts exactly that).
    let shell_sha = format!("{dir}/bash_program.sha256");
    println!("cargo:rerun-if-changed={shell_sha}");
    let sha: String = if kconfig_value("bash") {
        std::fs::read_to_string(&shell_sha)
            .map(|s| s.trim().to_string())
            .unwrap_or_default()
    } else {
        String::new()
    };
    gen.push_str(&format!(
        "pub static SHELL_IMAGE_SHA256: &str = {sha:?};\n"
    ));
    // P2: the first-party userland tools (tools/build-libc.sh) exec'd by dash.
    for (sym, file) in [("LS_ELF", "ls_program.bin"), ("CAT_ELF", "cat_program.bin")] {
        let path = format!("{dir}/{file}");
        println!("cargo:rerun-if-changed={path}");
        if std::path::Path::new(&path).exists() {
            gen.push_str(&format!("pub static {sym}: &[u8] = include_bytes!({path:?});\n"));
        } else {
            gen.push_str(&format!("pub static {sym}: &[u8] = &[];\n"));
        }
    }
    fs::write(format!("{out}/user_program.rs"), gen).unwrap();

    // 4. compile the assembly + C drivers into a static archive for the link.
    // The C code needs the same address-space model as the kernel: large code
    // model (0xFFFF8000... addresses) and no red zone (interrupts may push a
    // frame below rsp at any time).
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci_io.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/blk.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/i8042.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme_io.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/include/rust_core.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/include/driver.h");
    cc::Build::new()
        .file(format!("{dir}/../boot/entry.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/interrupts.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/isr_stubs.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/switch.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/syscall.S"))
        .file(format!("{dir}/../drivers/c/ahci.c"))
        .file(format!("{dir}/../drivers/c/ahci_io.c"))
        .file(format!("{dir}/../drivers/c/blk.c"))
        .file(format!("{dir}/../drivers/c/i8042.c"))
        .file(format!("{dir}/../drivers/c/nvme.c"))
        .file(format!("{dir}/../drivers/c/nvme_io.c"))
        .flag("-mcmodel=large")
        .flag("-mno-red-zone")
        .flag("-ffreestanding")
        .flag("-fno-stack-protector") // distro gcc defaults it on; we have no libc guard
        .include(format!("{dir}/../drivers/c/include"))
        .include(&out)
        .compile("bootobj");
}
