//! Build-time codegen (DESIGN.md §13.3):
//!   1. parse kernel/src/consts.rs -> OUT_DIR/asm_defs.inc (single source of
//!      truth for assembly constants),
//!   2. generate OUT_DIR/isr_table.rs (extern stubs + address table),
//!   3. compile boot/entry.S + kernel/src/arch/x86_64/asm/interrupts.S via cc (the host
//!      driver preprocesses them, so they can #include asm_defs.inc).
//! Also tracks link.ld so cargo relinks when it changes.

use std::env;
use std::fs;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tools/kconfig_emit.rs"));

fn main() {
    kconfig_emit();
    let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    println!("cargo:rerun-if-changed={dir}/link.ld");
    println!("cargo:rerun-if-changed={dir}/src/consts.rs");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/interrupts.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/isr_stubs.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/switch.S");
    println!("cargo:rerun-if-changed={dir}/src/arch/x86_64/asm/syscall.S");
    println!("cargo:rerun-if-changed={dir}/../boot/entry.S");
    println!("cargo:rustc-link-arg=-T{dir}/link.ld");

    let out = env::var("OUT_DIR").unwrap();

    // 1. asm_defs.inc: "pub const NAME: TYPE = VALUE;" -> ".equ NAME, VALUE"
    let consts = fs::read_to_string(format!("{dir}/src/consts.rs")).unwrap();
    let mut inc =
        String::from("/* Generated by kernel/build.rs from kernel/src/consts.rs - do not edit. */\n");
    for line in consts.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("pub const ") {
            let eq = rest.find('=').unwrap();
            let name = rest[..eq].split(':').next().unwrap().trim();
            let value = rest[eq + 1..].trim_end_matches(';').trim().replace('_', "");
            inc.push_str(&format!(".equ {name}, {value}\n"));
        }
    }
    fs::write(format!("{out}/asm_defs.inc"), inc).unwrap();

    // 2. isr_table.rs: extern stubs + a 256-entry address table
    let mut table = String::from("// Generated by kernel/build.rs - do not edit.\n\n");
    table.push_str("extern \"C\" {\n");
    for n in 0..256u16 {
        table.push_str(&format!("    fn isr_{n}();\n"));
    }
    table.push_str("}\n\npub fn isr_addresses() -> [u64; 256] {\n    [\n");
    for n in 0..256u16 {
        table.push_str(&format!("        isr_{n} as *const () as usize as u64,\n"));
    }
    table.push_str("    ]\n}\n");
    fs::write(format!("{out}/isr_table.rs"), table).unwrap();

    // 3. embed the user program (built by tools/build.sh before the kernel).
    // P1: the libc-fantuan C hello (tools/build-libc.sh) is embedded when
    // present; a missing artifact leaves HELLO_ELF empty so default builds
    // are unchanged.
    let user = format!("{dir}/user_program.bin");
    println!("cargo:rerun-if-changed={user}");
    if !std::path::Path::new(&user).exists() {
        panic!(
            "kernel/user_program.bin is missing — build the user crate first (tools/build.sh or tools/run.sh)"
        );
    }
    let hello = format!("{dir}/hello_program.bin");
    println!("cargo:rerun-if-changed={hello}");
    let mut gen = format!("pub static USER_ELF: &[u8] = include_bytes!({user:?});\n");
    if std::path::Path::new(&hello).exists() {
        gen.push_str(&format!("pub static HELLO_ELF: &[u8] = include_bytes!({hello:?});\n"));
    } else {
        gen.push_str("pub static HELLO_ELF: &[u8] = &[];\n");
    }
    // P2: the process-layer test program (user/proc_test.c) shares the hello
    // embedding path; absent builds skip the P2 smoke markers.
    let proc_test = format!("{dir}/proc_test_program.bin");
    println!("cargo:rerun-if-changed={proc_test}");
    if std::path::Path::new(&proc_test).exists() {
        gen.push_str(&format!("pub static PROC_ELF: &[u8] = include_bytes!({proc_test:?});\n"));
    } else {
        gen.push_str("pub static PROC_ELF: &[u8] = &[];\n");
    }
    // P2: /bin/dash (tools/build-dash.sh, vendored BSD-3-Clause) is embedded
    // the same way; absent, the registry stays empty and `sh` falls back.
    let dash = format!("{dir}/dash_program.bin");
    println!("cargo:rerun-if-changed={dash}");
    if std::path::Path::new(&dash).exists() {
        gen.push_str(&format!("pub static DASH_ELF: &[u8] = include_bytes!({dash:?});\n"));
    } else {
        gen.push_str("pub static DASH_ELF: &[u8] = &[];\n");
    }
    fs::write(format!("{out}/user_program.rs"), gen).unwrap();

    // 4. compile the assembly + C drivers into a static archive for the link.
    // The C code needs the same address-space model as the kernel: large code
    // model (0xFFFF8000... addresses) and no red zone (interrupts may push a
    // frame below rsp at any time).
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/ahci_io.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/blk.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/i8042.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/nvme_io.c");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/include/rust_core.h");
    println!("cargo:rerun-if-changed={dir}/../drivers/c/include/driver.h");
    cc::Build::new()
        .file(format!("{dir}/../boot/entry.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/interrupts.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/isr_stubs.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/switch.S"))
        .file(format!("{dir}/src/arch/x86_64/asm/syscall.S"))
        .file(format!("{dir}/../drivers/c/ahci.c"))
        .file(format!("{dir}/../drivers/c/ahci_io.c"))
        .file(format!("{dir}/../drivers/c/blk.c"))
        .file(format!("{dir}/../drivers/c/i8042.c"))
        .file(format!("{dir}/../drivers/c/nvme.c"))
        .file(format!("{dir}/../drivers/c/nvme_io.c"))
        .flag("-mcmodel=large")
        .flag("-mno-red-zone")
        .flag("-ffreestanding")
        .flag("-fno-stack-protector") // distro gcc defaults it on; we have no libc guard
        .include(format!("{dir}/../drivers/c/include"))
        .include(&out)
        .compile("bootobj");
}
