//! Deterministic `grub.cfg` generation (M7.9, DESIGN.md §9.1) from the /boot
//! inventory. No shell evaluation, fixed entry order, fixed buffers: the
//! output is a function of the inventory and the root UUID.

use super::bootfiles::{ImageName, Inventory};

pub const GEN_MAX: usize = 1024;

pub struct Generated {
    pub data: [u8; GEN_MAX],
    pub len: usize,
}

/// Bounds-checked writer over the fixed output buffer.
struct Cursor<'a> {
    buf: &'a mut [u8],
    n: usize,
}

impl Cursor<'_> {
    fn put(&mut self, b: &[u8]) -> Option<()> {
        if self.n + b.len() > self.buf.len() {
            return None;
        }
        self.buf[self.n..self.n + b.len()].copy_from_slice(b);
        self.n += b.len();
        Some(())
    }
}

/// Latest kernel name (lexicographic max approximates the newest version).
fn pick_latest<'a>(images: &'a [ImageName]) -> Option<&'a ImageName> {
    let mut best: Option<&ImageName> = None;
    for im in images {
        if im.len == 0 {
            continue;
        }
        match best {
            Some(b) if b.name[..b.len] >= im.name[..im.len] => {}
            _ => best = Some(im),
        }
    }
    best
}

/// The initrd matching a kernel name: the kernel's version suffix (after
/// "vmlinuz-") must appear in the initrd name.
fn match_initrd<'a>(initrds: &'a [ImageName], kernel: &[u8]) -> Option<&'a ImageName> {
    let suffix = kernel.strip_prefix(b"vmlinuz-").unwrap_or(kernel);
    initrds
        .iter()
        .find(|im| im.len > 0 && im.name[..im.len].windows(suffix.len()).any(|w| w == suffix))
}

/// Sanitize a text field for a single-quoted GRUB string: printable ASCII
/// except the quote, no control bytes.
fn sanitized(dst: &mut [u8], src: &[u8]) -> usize {
    let mut n = 0;
    for &b in src {
        if n >= dst.len() {
            break;
        }
        let c = if (0x20..0x7F).contains(&b) && b != b'\'' { b } else { b'_' };
        dst[n] = c;
        n += 1;
    }
    n
}

/// Generate the configuration for the mounted root UUID. Returns None when
/// there is no kernel to boot.
pub fn generate(inv: &Inventory, uuid: &[u8; 36]) -> Option<Generated> {
    let kernel = pick_latest(&inv.kernels[..inv.kernel_count])?;
    let initrd = match_initrd(&inv.initrds[..inv.initrd_count], &kernel.name[..kernel.len]);

    let mut os_id = [0u8; 32];
    let os_len = sanitized(&mut os_id, &inv.os_id[..inv.os_id_len]);
    let os_id = if os_len == 0 { &b"Linux"[..] } else { &os_id[..os_len] };

    let mut data = [0u8; GEN_MAX];
    let mut c = Cursor { buf: &mut data, n: 0 };
    c.put(b"# Generated by fantuan-kernel (M7.9) - do not edit\n")?;
    c.put(b"search --no-floppy --fs-uuid --set=root ")?;
    c.put(uuid)?;
    c.put(b"\n")?;
    c.put(b"set prefix=($root)/boot/grub\n")?;
    c.put(b"menuentry 'Fantuan rescue: ")?;
    c.put(os_id)?;
    c.put(b"' {\n")?;
    c.put(b"  linux /boot/")?;
    c.put(&kernel.name[..kernel.len])?;
    c.put(b" root=UUID=")?;
    c.put(uuid)?;
    c.put(b" ro")?;
    if inv.cmdline_len > 0 {
        let mut cmd = [0u8; 128];
        let cmd_len = sanitized(&mut cmd, &inv.cmdline[..inv.cmdline_len]);
        c.put(b" ")?;
        c.put(&cmd[..cmd_len])?;
    }
    c.put(b"\n")?;
    if let Some(initrd) = initrd {
        c.put(b"  initrd /boot/")?;
        c.put(&initrd.name[..initrd.len])?;
        c.put(b"\n")?;
    }
    c.put(b"}\n")?;
    let len = c.n;
    drop(c); // end the borrow before moving DATA into the result
    Some(Generated { data, len })
}
