//! `grub-fix install` (M7.9, DESIGN.md §9.1): regenerate the boot
//! configuration. Order: inventory -> target -> backup (verified) ->
//! publish -> re-read verify -> fallback chain -> NVRAM entry. Every write
//! goes through the RepairToken gate; a failed backup aborts before anything
//! is overwritten.

use core::fmt::Write;

use crate::serial::Serial;
use crate::vfs::ext4::guid_text;
use crate::vfs::{self, fat::Fat32, Vfs};

use super::{bootfiles, find_dir, grubgen};

/// Backup/publish streams in 4 KiB windows; configs are tiny.
const IO_BUF: usize = 4096;
/// Backups larger than this are refused (a grub.cfg is never 64 KiB).
const BACKUP_MAX: usize = 64 * 1024;

static mut COPY_BUF: [u8; IO_BUF] = [0; IO_BUF];

struct Target {
    dir: u32,
    name: [u8; 11],
    path: &'static str,
}

fn dir_has_file(fs: &Fat32, dir: u32, name: &[u8; 11]) -> bool {
    let mut found = false;
    fs.walk_dir(dir, |n, attr, _c, _s| {
        if !found && vfs::eq_8_3(n, name) && attr & 0x10 == 0 {
            found = true;
        }
    });
    found
}

fn entry_of(fs: &Fat32, dir: u32, name: &[u8; 11]) -> Option<(u32, u32)> {
    let mut found = None;
    fs.walk_dir(dir, |n, attr, cluster, size| {
        if found.is_none() && vfs::eq_8_3(n, name) && attr & 0x10 == 0 {
            found = Some((cluster, size));
        }
    });
    found
}

/// Vendor config first (ubuntu, then debian), else EFI/fantuan (created).
fn choose_target(s: &mut Serial, vfs: &Vfs, token: &vfs::RepairToken) -> Option<Target> {
    let fs = &vfs.fs;
    let efi = vfs::to_8_3("EFI")?;
    let cfg = vfs::to_8_3("grub.cfg")?;
    let Some(efi_dir) = find_dir(fs, fs.root_cluster, &efi) else {
        let _ = writeln!(s, "install: no EFI directory on the ESP");
        return None;
    };
    for (path, vendor) in [("EFI/ubuntu/grub.cfg", "ubuntu"), ("EFI/debian/grub.cfg", "debian")] {
        let vname = vfs::to_8_3(vendor)?;
        if let Some(dir) = find_dir(fs, efi_dir, &vname) {
            if dir_has_file(fs, dir, &cfg) {
                return Some(Target { dir, name: cfg, path });
            }
        }
    }
    let fantuan = vfs::to_8_3("fantuan")?;
    let dir = fs.find_or_create_dir(efi_dir, &fantuan, token)?;
    Some(Target { dir, name: cfg, path: "EFI/fantuan/grub.cfg" })
}

/// Copy the existing target to GRUBCFG.BAK (streaming) and verify size +
/// content by re-reading. Ok(false) = nothing to back up.
fn backup_existing(s: &mut Serial, fs: &Fat32, target: &Target, token: &vfs::RepairToken) -> Result<bool, ()> {
    let Some((cluster, size)) = entry_of(fs, target.dir, &target.name) else {
        return Ok(false);
    };
    if size as usize > BACKUP_MAX {
        let _ = writeln!(s, "install: existing config is {} bytes (> {}), refusing to back it up", size, BACKUP_MAX);
        return Err(());
    }
    let bak = vfs::to_8_3("grubcfg.bak").ok_or(())?;
    let Some(mut w) = fs.create_file(target.dir, &bak, token) else {
        return Err(());
    };
    let buf = unsafe { &mut *core::ptr::addr_of_mut!(COPY_BUF) };
    let mut off = 0usize;
    while off < size as usize {
        let n = (size as usize - off).min(IO_BUF);
        let Some(got) = fs.read_range(cluster, off as u64, &mut buf[..n]) else {
            return Err(());
        };
        if got == 0 || !w.append(&buf[..got]) {
            return Err(());
        }
        off += got;
    }
    if !w.finish() {
        return Err(());
    }
    let Some((bcluster, bsize)) = entry_of(fs, target.dir, &bak) else {
        return Err(());
    };
    if bsize != size || !files_equal(fs, cluster, size, bcluster, bsize) {
        let _ = writeln!(s, "install: backup verify FAILED ({} vs {} bytes)", size, bsize);
        return Err(());
    }
    let _ = writeln!(s, "install: backed up {} -> GRUBCFG.BAK ({} bytes, verified)", target.path, size);
    Ok(true)
}

/// Stream-compare two files in IO_BUF windows.
fn files_equal(fs: &Fat32, a: u32, a_size: u32, b: u32, b_size: u32) -> bool {
    if a_size != b_size {
        return false;
    }
    let buf = unsafe { &mut *core::ptr::addr_of_mut!(COPY_BUF) };
    let mut off = 0usize;
    while off < a_size as usize {
        let n = (a_size as usize - off).min(IO_BUF);
        if fs.read_range(a, off as u64, &mut buf[..n]).unwrap_or(0) != n {
            return false;
        }
        let mut other = [0u8; IO_BUF];
        if fs.read_range(b, off as u64, &mut other[..n]).unwrap_or(0) != n {
            return false;
        }
        if buf[..n] != other[..n] {
            return false;
        }
        off += n;
    }
    true
}

/// Publish the generated bytes, then re-read and compare.
fn publish(s: &mut Serial, vfs: &Vfs, target: &Target, gen: &grubgen::Generated) -> bool {
    if !vfs::write_file(&vfs.fs, target.dir, &target.name, &gen.data[..gen.len]) {
        let _ = writeln!(s, "install: publish failed ({})", target.path);
        return false;
    }
    let Some((cluster, size)) = entry_of(&vfs.fs, target.dir, &target.name) else {
        let _ = writeln!(s, "install: published but the entry vanished");
        return false;
    };
    let mut back = [0u8; grubgen::GEN_MAX];
    let Some(n) = vfs.fs.read_file(cluster, size, &mut back) else {
        let _ = writeln!(s, "install: published but re-read failed");
        return false;
    };
    if n != gen.len || back[..n] != gen.data[..gen.len] {
        let _ = writeln!(s, "install: verify MISMATCH ({} bytes written, {} read back)", gen.len, n);
        return false;
    }
    let _ = writeln!(s, "install: wrote {} ({} bytes, verified)", target.path, gen.len);
    true
}

pub fn run(s: &mut Serial, vfs: &Vfs, runtime_services: u64) {
    let Some(token) = vfs::repair_guard() else {
        let _ = writeln!(s, "install: refused — repair mode is off (explicit consent required)");
        return;
    };
    let _ = writeln!(s, "install: regenerating the boot configuration (M7.9)");

    let Some(root) = vfs.root.as_ref() else {
        let _ = writeln!(s, "install: no ext4 root — cannot generate a configuration");
        return;
    };
    let inventory = bootfiles::scan(s, root);
    let uuid = guid_text(&root.uuid);
    let Some(gen) = grubgen::generate(&inventory, &uuid) else {
        let _ = writeln!(s, "install: no kernel found under /boot — nothing to generate");
        return;
    };
    let Some(target) = choose_target(s, vfs, &token) else {
        let _ = writeln!(s, "install: cannot determine a target configuration path");
        return;
    };
    let _ = writeln!(s, "install: target {}", target.path);

    match backup_existing(s, &vfs.fs, &target, &token) {
        Ok(_) => {}
        Err(()) => {
            let _ = writeln!(s, "install: ABORTED — backup failed, nothing overwritten");
            return;
        }
    }
    if !publish(s, vfs, &target, &gen) {
        return;
    }

    // Chain + NVRAM entry (both repair-gated; the fallback copy is a no-op
    // when BOOTX64.EFI already exists).
    super::fix_missing_fallback(s, vfs);
    if let Some(rt) = crate::runtime::Runtime::new(runtime_services) {
        super::nvram_repair::repair(s, &rt, vfs);
    } else {
        let _ = writeln!(s, "install: runtime services unavailable — NVRAM entry not checked");
    }

    let _ = write!(s, "install: done — boot chain: ");
    let _ = writeln!(s, "{} + ESP payloads + NVRAM entry", target.path);
}
