#!/usr/bin/env python3
"""Kconfig fragment generation for tools/appctl (C2)."""
import os

import app_lock
from app_manifest import parse, unmet_requires
from app_util import app_symbol

GENERATED = "# Generated by tools/appctl menu - do not edit."


def _clean(text):
    return " ".join(str(text).split()).replace('"', "'")


def fragment(name, manifest, unavailable=()):
    gpl = bool(manifest.get("gpl", False))
    suffix = ""
    if unavailable:
        suffix = " (unavailable: requires " + ", ".join(unavailable) + ")"
    lines = [
        GENERATED,
        f"config {app_symbol(name)}",
        f'    bool "{name}: {_clean(manifest["description"])}{suffix}"',
        "    default n",
        "    help",
        f"        {_clean(manifest['description'])}",
    ]
    if unavailable:
        lines.append(
            "        unavailable until the required layer lands: requires "
            + ", ".join(unavailable)
            + "; this symbol stays default n."
        )
    lines.append(
        f"        version {_clean(manifest['version'])}, license {_clean(manifest['license'])}, "
        f"gpl={'true' if gpl else 'false'}."
    )
    return "\n".join(lines) + "\n"


def generate(root, catalog):
    config_dir = os.path.join(root, "config", "apps")
    os.makedirs(config_dir, exist_ok=True)
    entries = app_lock.load(os.path.join(root, "apps.lock"))
    allow = catalog.gpl_allow() if catalog else []
    written, skipped, notes = [], [], []
    for entry in entries:
        name = entry["name"]
        manifest_path = os.path.join(root, "apps", name, "manifest.toml")
        if not os.path.isfile(manifest_path):
            skipped.append((name, "vendored tree missing"))
            continue
        manifest = parse(manifest_path)
        if bool(manifest.get("gpl", False)) and name not in allow:
            skipped.append((name, "GPL not in the apps-layer allow list"))
            continue
        unavailable = unmet_requires(manifest)
        if unavailable:
            notes.append((name, "requires " + ", ".join(unavailable)))
        with open(os.path.join(config_dir, f"{name}.kconfig"), "w", encoding="utf-8") as handle:
            handle.write(fragment(name, manifest, unavailable))
        written.append(name)
    keep = {f"{name}.kconfig" for name in written}
    for existing in sorted(os.listdir(config_dir)):
        path = os.path.join(config_dir, existing)
        if existing in keep or not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as handle:
            if handle.readline().strip() == GENERATED:
                os.remove(path)
    return written, skipped, notes
