#!/usr/bin/env bash
# P2 dash builder (docs/POSIX_PLAN.md): cross-compile the vendored pristine
# dash 0.5.12 (BSD-3-Clause, apps/dash/) against libc-fantuan for the
# x86_64-unknown-none target and link the static ELF.
#
#   tools/build-dash.sh            # build build/dash/dash.elf
#   DASH_VERIFY=1 tools/build-dash.sh   # rebuild and compare hashes
#
# Outputs: build/dash/{dash.elf,config.h,objects/,blockers.txt}; on success
# kernel/dash_program.bin (embedded by kernel/build.rs when present).
#
# The configure-free build: dash's autoconf probes cannot link freestanding
# programs, so this script writes the config.h the probes would produce and
# builds the host-side generators (mkinit/mksyntax/mknodes/mksignames) with
# the host compiler. Everything else is plain C against libc-fantuan.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TARBALL="$ROOT/apps/dash/src/dash-0.5.12.tar.gz"
OUT="$ROOT/build/dash"
SRC="$OUT/src/dash-0.5.12"
CC="${DASH_CC:-clang}"
HOSTCC="${DASH_HOSTCC:-cc}"
AR="${DASH_AR:-llvm-ar}"
TARGET="${DASH_TARGET:-x86_64-unknown-none}"
VERIFY="${DASH_VERIFY:-0}"
BLOCKERS="$OUT/blockers.txt"

mkdir -p "$OUT"
rm -f "$BLOCKERS"

command -v "$CC" >/dev/null 2>&1 || { echo "build-dash: $CC not found" >&2; exit 2; }
[ -f "$TARBALL" ] || { echo "build-dash: $TARBALL missing (run tools/fetch-bash-src.sh for the shell sources)" >&2; exit 2; }

# Incremental skip, like build-bash.sh: the default build calls this on every
# tools/build.sh run, so reuse the binary while the inputs are unchanged.
# DASH_FORCE=1 or DASH_VERIFY=1 rebuilds.
stamp_value() {
  sha256sum "$TARBALL" "$ROOT/build/libc-fantuan/libc-fantuan.a" "$0" 2>/dev/null \
    | cut -d' ' -f1 | sha256sum | cut -d' ' -f1
}
STAMP="$OUT/.stamp"
WANT_STAMP="$(stamp_value)"
if [ "${DASH_FORCE:-0}" != "1" ] && [ "$VERIFY" != "1" ] \
   && [ -f "$OUT/dash.elf" ] && [ "$(cat "$STAMP" 2>/dev/null || true)" = "$WANT_STAMP" ]; then
  echo "[dash] up to date (tarball and libc unchanged); reusing build/dash/dash.elf"
  mkdir -p "$ROOT/kernel"
  cmp -s "$OUT/dash.elf" "$ROOT/kernel/dash_program.bin" \
    || cp "$OUT/dash.elf" "$ROOT/kernel/dash_program.bin"
  exit 0
fi

# --- sources + config.h -----------------------------------------------------
rm -rf "$SRC"
mkdir -p "$SRC"
tar xzf "$TARBALL" -C "$OUT/src"
[ -f "$SRC/src/main.c" ] || { echo "build-dash: unexpected tarball layout" >&2; exit 2; }

cat > "$OUT/config.h" <<'EOF'
/* Generated by tools/build-dash.sh for dash 0.5.12 on the fantuan native
 * ABI. This is the autoconf feature set of libc-fantuan (P2). */
#define HAVE_ALIAS_ATTRIBUTE 1
#define HAVE_ALLOCA_H 1
#define HAVE_BSEARCH 1
#define HAVE_DECL_ISBLANK 1
#define HAVE_GETPWNAM 1
#define HAVE_GETRLIMIT 1
#define HAVE_ISALPHA 1
#define HAVE_KILLPG 1
#define HAVE_MEMPCPY 1
#define HAVE_PATHS_H 1
#define HAVE_STPCPY 1
#define HAVE_STRCHRNUL 1
#define HAVE_STRSIGNAL 1
#define HAVE_STRTOD 1
#define HAVE_STRTOIMAX 1
#define HAVE_STRTOUMAX 1
#define HAVE_SYSCONF 1
#define WITH_LINENO 1
#define SMALL 1
/* No 64-bit LFS variants on the native ABI: the configure fallbacks. */
#define stat64 stat
#define lstat64 lstat
#define fstat64 fstat
#define open64 open
#define readdir64 readdir
#define dirent64 dirent
#define glob64 glob
#define glob64_t glob_t
/* Not defined on purpose: HAVE_FNMATCH (dash uses its bundled pmatch),
 * HAVE_GLOB, HAVE_FACCESSAT, HAVE_SIGSETMASK, HAVE_ST_MTIM. */
EOF
cp "$OUT/config.h" "$SRC/config.h"

RES_INC="$("$CC" -print-resource-dir)/include"
INC="$ROOT/libc-fantuan/include"

# --- host generators (builtins.def pipeline) --------------------------------
# token.h comes first: mksyntax needs it at compile time.
run_in_src() { (cd "$SRC/src" && "$@") >> "$BLOCKERS" 2>&1; }
run_in_src sh mktokens

HGEN=("-DBSD=1" "-DSHELL" "-I$SRC/src")
for tool in mkinit mksyntax mknodes mksignames; do
  if ! "$HOSTCC" -O2 "${HGEN[@]}" -o "$OUT/$tool" "$SRC/src/$tool.c" 2>> "$BLOCKERS"; then
    echo "build-dash: host generator $tool failed to build" >&2
    echo "BLOCKER: host generator $tool failed (see $BLOCKERS)" >> "$BLOCKERS"
    exit 1
  fi
done

CFLAGS=(
  "--target=$TARGET" -ffreestanding -nostdinc -isystem "$RES_INC" -I "$INC" -I "$SRC/src"
  -include "$SRC/config.h" -DBSD=1 -DSHELL
  -fno-builtin -fno-stack-protector -fno-pic -fno-pie -mno-red-zone
  -fno-asynchronous-unwind-tables -fno-unwind-tables -O2 -Wall -Wextra
)

# builtins.def through the target preprocessor (config.h matters).
"$CC" "--target=$TARGET" -ffreestanding -nostdinc -isystem "$RES_INC" -I "$INC" \
  -include "$SRC/config.h" -DBSD=1 -DSHELL -E -x c -o "$SRC/src/builtins.def" \
  "$SRC/src/builtins.def.in" >> "$BLOCKERS" 2>&1 || {
    echo "build-dash: builtins.def preprocessing failed" >&2; exit 1; }

run_in_src sh mkbuiltins builtins.def
run_in_src "$OUT/mkinit" alias.c arith_yacc.c arith_yylex.c cd.c error.c eval.c exec.c \
  expand.c histedit.c input.c jobs.c mail.c main.c memalloc.c miscbltin.c \
  mystring.c options.c parser.c redir.c show.c trap.c output.c bltin/printf.c \
  system.c bltin/test.c bltin/times.c var.c
run_in_src "$OUT/mknodes" nodetypes nodes.c.pat
run_in_src "$OUT/mksyntax"
run_in_src "$OUT/mksignames"

DASH_CFILES=(alias arith_yacc arith_yylex cd error eval exec expand histedit input
  jobs mail main memalloc miscbltin mystring options parser redir show trap output
  var builtins init nodes signames syntax)
CFILES_EXTRA=(bltin/printf system bltin/test bltin/times)

OBJ="$OUT/obj"
rm -rf "$OBJ"
mkdir -p "$OBJ/bltin"

ok=1
compile() { # src relout
  local src="$1" rel="$2"
  if ! "$CC" "${CFLAGS[@]}" -c "$SRC/src/$src" -o "$OBJ/$rel.o" 2>> "$BLOCKERS"; then
    echo "BLOCKER: compile $src failed" >> "$BLOCKERS"
    ok=0
  fi
}
for f in "${DASH_CFILES[@]}"; do compile "$f.c" "$f"; done
for f in "${CFILES_EXTRA[@]}"; do compile "$f.c" "${f//\//_}"; done
if ! "$CC" "--target=$TARGET" -ffreestanding -nostdinc -isystem "$RES_INC" -I "$INC" \
  -fno-builtin -fno-stack-protector -fno-pic -fno-pie -mno-red-zone -c \
  "$ROOT/libc-fantuan/src/crt0.S" -o "$OBJ/crt0.o" 2>> "$BLOCKERS"; then
  echo "BLOCKER: crt0 compile failed" >> "$BLOCKERS"
  ok=0
fi

if [ "$ok" != "1" ]; then
  echo "build-dash: dash does not compile against libc-fantuan (P2)" >&2
  grep -c "^BLOCKER" "$BLOCKERS" >/dev/null 2>&1 || true
  tail -30 "$BLOCKERS" >&2
  exit 1
fi

"$AR" rcsD "$OUT/libdash.a" "$OBJ"/*.o
# Every dash object is passed explicitly; crt0 and libc resolve in one pass
# with --start-group (the archive members reference each other).
"$CC" --target="$TARGET" -nostdlib -static -no-pie \
  -Wl,--build-id=none -Wl,--gc-sections \
  -Wl,-T,"$ROOT/libc-fantuan/elf.ld" \
  -Wl,--start-group "$OBJ"/*.o \
  "$ROOT/build/libc-fantuan/libc-fantuan.a" -Wl,--end-group \
  -o "$OUT/dash.elf" >> "$BLOCKERS" 2>&1 || {
    echo "build-dash: link failed" >&2; tail -30 "$BLOCKERS" >&2; exit 1; }

if [ "$VERIFY" = "1" ]; then
  sha1=$(sha256sum "$OUT/dash.elf" | awk '{print $1}')
  "$0" >/dev/null 2>&1
  sha2=$(sha256sum "$OUT/dash.elf" | awk '{print $1}')
  if [ "$sha1" != "$sha2" ]; then
    echo "build-dash: NOT deterministic ($sha1 != $sha2)" >&2
    exit 1
  fi
  echo "[dash] deterministic: $sha1"
fi

mkdir -p "$ROOT/kernel"
cmp -s "$OUT/dash.elf" "$ROOT/kernel/dash_program.bin" \
  || cp "$OUT/dash.elf" "$ROOT/kernel/dash_program.bin"
printf '%s\n' "$WANT_STAMP" > "$STAMP"

echo "[dash] build/dash/dash.elf $(stat -c %s "$OUT/dash.elf") bytes -> kernel/dash_program.bin"
